// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PullRequest.proto

package com.ruqinhu;

public interface PullRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PullRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool isReadOnlySafe = 1;</code>
   */
  boolean getIsReadOnlySafe();
}
