// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterResponse.proto

package com.ruqinhu;

/**
 * Protobuf type {@code RegisterResponse}
 */
public  final class RegisterResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RegisterResponse)
    RegisterResponseOrBuilder {
  // Use RegisterResponse.newBuilder() to construct.
  private RegisterResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterResponse() {
    success_ = false;
    redirect_ = "";
    errorMsg_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RegisterResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              value_ = com.google.protobuf.MapField.newMapField(
                  ValueDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            value = input.readMessage(
                ValueDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            value_.getMutableMap().put(value.getKey(), value.getValue());
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            redirect_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMsg_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ruqinhu.RegisterResponseProto.internal_static_RegisterResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetValue();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ruqinhu.RegisterResponseProto.internal_static_RegisterResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ruqinhu.RegisterResponse.class, com.ruqinhu.RegisterResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>optional bool success = 1;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private static final class ValueDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.ruqinhu.RegisterResponseProto.internal_static_RegisterResponse_ValueEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> value_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetValue() {
    if (value_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValueDefaultEntryHolder.defaultEntry);
    }
    return value_;
  }

  public int getValueCount() {
    return internalGetValue().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */

  public boolean containsValue(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetValue().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValueMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getValue() {
    return getValueMap();
  }
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getValueMap() {
    return internalGetValue().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */

  public java.lang.String getValueOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetValue().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */

  public java.lang.String getValueOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetValue().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int REDIRECT_FIELD_NUMBER = 3;
  private volatile java.lang.Object redirect_;
  /**
   * <code>optional string redirect = 3;</code>
   */
  public java.lang.String getRedirect() {
    java.lang.Object ref = redirect_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      redirect_ = s;
      return s;
    }
  }
  /**
   * <code>optional string redirect = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRedirectBytes() {
    java.lang.Object ref = redirect_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      redirect_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORMSG_FIELD_NUMBER = 4;
  private volatile java.lang.Object errorMsg_;
  /**
   * <code>optional string errorMsg = 4;</code>
   */
  public java.lang.String getErrorMsg() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMsg_ = s;
      return s;
    }
  }
  /**
   * <code>optional string errorMsg = 4;</code>
   */
  public com.google.protobuf.ByteString
      getErrorMsgBytes() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetValue().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      value = ValueDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      output.writeMessage(2, value);
    }
    if (!getRedirectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, redirect_);
    }
    if (!getErrorMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorMsg_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetValue().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      value = ValueDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, value);
    }
    if (!getRedirectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, redirect_);
    }
    if (!getErrorMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorMsg_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ruqinhu.RegisterResponse)) {
      return super.equals(obj);
    }
    com.ruqinhu.RegisterResponse other = (com.ruqinhu.RegisterResponse) obj;

    boolean result = true;
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && internalGetValue().equals(
        other.internalGetValue());
    result = result && getRedirect()
        .equals(other.getRedirect());
    result = result && getErrorMsg()
        .equals(other.getErrorMsg());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (!internalGetValue().getMap().isEmpty()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValue().hashCode();
    }
    hash = (37 * hash) + REDIRECT_FIELD_NUMBER;
    hash = (53 * hash) + getRedirect().hashCode();
    hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMsg().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ruqinhu.RegisterResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ruqinhu.RegisterResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ruqinhu.RegisterResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ruqinhu.RegisterResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ruqinhu.RegisterResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RegisterResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RegisterResponse)
      com.ruqinhu.RegisterResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ruqinhu.RegisterResponseProto.internal_static_RegisterResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetValue();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableValue();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ruqinhu.RegisterResponseProto.internal_static_RegisterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ruqinhu.RegisterResponse.class, com.ruqinhu.RegisterResponse.Builder.class);
    }

    // Construct using com.ruqinhu.RegisterResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      success_ = false;

      internalGetMutableValue().clear();
      redirect_ = "";

      errorMsg_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ruqinhu.RegisterResponseProto.internal_static_RegisterResponse_descriptor;
    }

    public com.ruqinhu.RegisterResponse getDefaultInstanceForType() {
      return com.ruqinhu.RegisterResponse.getDefaultInstance();
    }

    public com.ruqinhu.RegisterResponse build() {
      com.ruqinhu.RegisterResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ruqinhu.RegisterResponse buildPartial() {
      com.ruqinhu.RegisterResponse result = new com.ruqinhu.RegisterResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.success_ = success_;
      result.value_ = internalGetValue();
      result.value_.makeImmutable();
      result.redirect_ = redirect_;
      result.errorMsg_ = errorMsg_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ruqinhu.RegisterResponse) {
        return mergeFrom((com.ruqinhu.RegisterResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ruqinhu.RegisterResponse other) {
      if (other == com.ruqinhu.RegisterResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      internalGetMutableValue().mergeFrom(
          other.internalGetValue());
      if (!other.getRedirect().isEmpty()) {
        redirect_ = other.redirect_;
        onChanged();
      }
      if (!other.getErrorMsg().isEmpty()) {
        errorMsg_ = other.errorMsg_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ruqinhu.RegisterResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ruqinhu.RegisterResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>optional bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool success = 1;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> value_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValue() {
      if (value_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValueDefaultEntryHolder.defaultEntry);
      }
      return value_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableValue() {
      onChanged();;
      if (value_ == null) {
        value_ = com.google.protobuf.MapField.newMapField(
            ValueDefaultEntryHolder.defaultEntry);
      }
      if (!value_.isMutable()) {
        value_ = value_.copy();
      }
      return value_;
    }

    public int getValueCount() {
      return internalGetValue().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */

    public boolean containsValue(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValue().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValueMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValue() {
      return getValueMap();
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getValueMap() {
      return internalGetValue().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */

    public java.lang.String getValueOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValue().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */

    public java.lang.String getValueOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValue().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearValue() {
      getMutableValue().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */

    public Builder removeValue(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      getMutableValue().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableValue() {
      return internalGetMutableValue().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */
    public Builder putValue(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      getMutableValue().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; value = 2;</code>
     */

    public Builder putAllValue(
        java.util.Map<java.lang.String, java.lang.String> values) {
      getMutableValue().putAll(values);
      return this;
    }

    private java.lang.Object redirect_ = "";
    /**
     * <code>optional string redirect = 3;</code>
     */
    public java.lang.String getRedirect() {
      java.lang.Object ref = redirect_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redirect_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string redirect = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRedirectBytes() {
      java.lang.Object ref = redirect_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirect_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string redirect = 3;</code>
     */
    public Builder setRedirect(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      redirect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string redirect = 3;</code>
     */
    public Builder clearRedirect() {
      
      redirect_ = getDefaultInstance().getRedirect();
      onChanged();
      return this;
    }
    /**
     * <code>optional string redirect = 3;</code>
     */
    public Builder setRedirectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      redirect_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errorMsg_ = "";
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public Builder setErrorMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public Builder clearErrorMsg() {
      
      errorMsg_ = getDefaultInstance().getErrorMsg();
      onChanged();
      return this;
    }
    /**
     * <code>optional string errorMsg = 4;</code>
     */
    public Builder setErrorMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMsg_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:RegisterResponse)
  }

  // @@protoc_insertion_point(class_scope:RegisterResponse)
  private static final com.ruqinhu.RegisterResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ruqinhu.RegisterResponse();
  }

  public static com.ruqinhu.RegisterResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterResponse>
      PARSER = new com.google.protobuf.AbstractParser<RegisterResponse>() {
    public RegisterResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegisterResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RegisterResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterResponse> getParserForType() {
    return PARSER;
  }

  public com.ruqinhu.RegisterResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

