// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterResponse.proto

package com.ruqinhu;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */
  int getValueCount();
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */
  boolean containsValue(
      java.lang.String key);
  /**
   * Use {@link #getValueMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getValue();
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getValueMap();
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */

  java.lang.String getValueOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; value = 2;</code>
   */

  java.lang.String getValueOrThrow(
      java.lang.String key);

  /**
   * <code>optional string redirect = 3;</code>
   */
  java.lang.String getRedirect();
  /**
   * <code>optional string redirect = 3;</code>
   */
  com.google.protobuf.ByteString
      getRedirectBytes();

  /**
   * <code>optional string errorMsg = 4;</code>
   */
  java.lang.String getErrorMsg();
  /**
   * <code>optional string errorMsg = 4;</code>
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();
}
